version: '3.8'

services:
  web:
    build: .
    container_name: simpleweb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000

  # Uncomment the following section if you want to add a reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: simpleweb_nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - web