name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:latest,${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:buildcache,mode=max

      # Deploy to a DigitalOcean Droplet with Docker
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            # Create directory for the app if it doesn not exist
            mkdir -p /opt/simpleweb
            
            # Copy docker-compose template to the server if it does not exist
            [ ! -f /opt/simpleweb/docker-compose.yml ] && cat > /opt/simpleweb/docker-compose.yml <<"EOL"
            version: "3.8"
            
            services:
              web:
                image: ${IMAGE_NAME}
                container_name: simpleweb
                restart: always
                ports:
                  - "8000:8000"
                environment:
                  - ENVIRONMENT=production
                  - LOG_LEVEL=info
            EOL
            
            # Pull the latest image and restart the service
            cd /opt/simpleweb
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:latest
            export IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/simpleweb:latest
            docker-compose up -d

      - name: Verify Deployment
        run: |
          echo "Deployed successfully to Digital Ocean!"
          echo "App URL: http://${{ secrets.DIGITALOCEAN_HOST }}:8000"